name: Auto Build and Release WRT
run-name: Auto Build - ${{ matrix.model }}

on:
  schedule:
    # 每天北京时间 0 点 (即 UTC 16:00) 触发
    - cron: "0 2 * * *"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  auto-build:
    strategy:
      matrix:
        model: [jdcloud_ipq60xx_immwrt, jdcloud_ipq60xx_libwrt]
    uses: ./.github/workflows/build_wrt.yml
    with:
      model: ${{ matrix.model }}
