name: Build WRT
run-name: Build - ${{ inputs.model }}

on:
  workflow_dispatch:
    inputs:
      model:
        required: true
        description: Device Model
        type: choice
        default: jdcloud_ipq60xx_immwrt
        options:
          - jdcloud_ipq60xx_immwrt
          - jdcloud_ipq60xx_libwrt
          
  workflow_call: 
    inputs:
      model:
        required: true
        type: string

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Save model for release
        run: echo "${{ inputs.model }}" > model.txt

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-model
          path: model.txt

      # ==== 这里还是你原来的构建步骤 ====
      - name: Build Firmware
        run: ./build.sh ${{ inputs.model }}

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: ./firmware/*.*
